### ISSUE TITLE
About the baselines

### ISSUE THREAD

**Issue by EchoTHChen** [KAIST-VCLAB/EgocentricReconstruction#1]
I see that the repo of colmap does not provide the scripts of running colmap on panoramas:https://github.com/colmap/colmap/issues/790.

How can I run colmap on the panoramas (such as the dataset your method runs on)?

**Comment by Hyeonjoong-Jang** [comment]
We converted each panorama into six cube-map images (120-degree FoV to make them overlap each other) that share the same camera position, then used them all.

**Comment by EchoTHChen** [comment]
I have another questions: For indoor scenes (there are many non-texture regions), the feature points extracted in the overlapped regions between cube-maps might be too few for COLMAP. So I think theoretically COLMAP might fail in some indoor scenes.

Could you share your scripts you generate the cube-maps and test on the sample data?(I just started learning panoramas recently and want to learn how COLMAP works for panorama?)

**Comment by Hyeonjoong-Jang** [comment]
I used py360convert. 
Please refer https://github.com/sunset1995/py360convert

As you can see in their document, we can convert them with e2p function as below.
`
fov=120
img = py360convert.e2p(frame, (fov, fov), -90, 0, (w,h), 0, 'bilinear')
`

**Comment by EchoTHChen** [comment]
Thanks!
