### ISSUE TITLE
Resolution should be a multiple of 8*32

### ISSUE THREAD

**Issue by ResonancePA** [KAIST-VCLAB/EgocentricReconstruction#5]
Hi, thank you for your work! 
It seems that the resolution of the video (height and width) should be a multiple of 8*32, otherwise there would be an error (like the one introduced in https://github.com/vt-vl-lab/FGVC/issues/41). Is this conclusion right? After changing the resolution of video the error is solved. Is there any other way to solve this?
Thank you very much!

**Comment by Hyeonjoong-Jang** [comment]
Hi, can you share the size of your video resolution, the line number, and the error messages? so that I can reproduce your error and try to solve this issue.

**Comment by ResonancePA** [comment]
> 

Hi, thank you very much for your reply! 
The resolution is 1440*720, line number in depth_util line 65, and the error message is like this : expected grid and input to have same batch size, but got input with sizes [3225, 1, 43, 75] and grid with sizes [3150, 9, 9, 2]
After changing it to 1024*512, it just works well.

**Comment by ResonancePA** [comment]
Also, is there anyway to run the program on CPU? Thanks a lot!

**Comment by Hyeonjoong-Jang** [comment]
Hi, 
The optical flow estimation network seems to require input image resolution of multiple of 8.
The value of the parameter depth_scale specified in the demo.json file, 0.5, resizes the input image, and the code expands the image to be 10 / 8 of the original before it estimates flow.
So the value [scale * 10 * W / 8] should be a multiple of 8, which explains the issue.
Please slightly resize your input.

Sorry, but I don't have CPU version of my code.

**Comment by ResonancePA** [comment]
Thank you very much! I just post this if others met this problem.
