### ISSUE TITLE
Using openMVG as a replace of openVSLAM

### ISSUE THREAD

**Issue by ResonancePA** [KAIST-VCLAB/EgocentricReconstruction#6]
Hi! Because the openVSLAM has been terminated, your paper said that openMVG would be a suitable replacement. Could you please tell me is there any difference between the two module (like the pose data structure or accuracy or something else)? I recently using openMVG to output the trajectory of camera and it seems really different from the example file you included in the demo. I wonder if I did something wrong in transfering the data structure or something else.
Thank you very much!

**Comment by Hyeonjoong-Jang** [comment]
Hi, 
There may be a difference in the file format. For example, they save 3x4 elements from 4x4 camera-to-world matrices, while my example file has 4x4 world-to-camera matrices.

**Comment by ResonancePA** [comment]
Thank you!
