### ISSUE TITLE
How to make reconstruction results better

### ISSUE THREAD

**Issue by ResonancePA** [KAIST-VCLAB/EgocentricReconstruction#9]
Hi, are there any suggestions to increase the quality of reconstruction results? Like forcing the camera's direction unchanged or making the trajectory a circle? And is there any material that would effect the result (like water, glass or something else)?

**Comment by Hyeonjoong-Jang** [comment]
Hi, materials that are transparent or cause specular reflections might lead to incorrect depth estimation.
There is no restriction on the camera trajectory. Still, if the camera motion is linear and does not rotate at all, it cannot reconstruct the surfaces along the baseline axis.

**Comment by ResonancePA** [comment]
Thanks a lot!
